### ISSUE TITLE
Splitting Semicolon is not enough.

### ISSUE THREAD

**Issue by z639** [RichardLitt/inline-style-2-json#1]
If the inline CSS contains an external background image or cursor url, then just splitting the semicolon will just break the url because there will be more than 2 splits in the array.

Also note that CSS3 now supports multiple background images.

https://developer.mozilla.org/en/docs/Web/CSS/CSS_Background_and_Borders/Using_CSS_multiple_backgrounds

For example entering the CSS - 

 "background:url(https://mdn.mozillademos.org/files/11305/firefox.png), url(https://mdn.mozillademos.org/files/11307/bubbles.png)" 

Would return Object {background: "url(https"}

**Comment by z639** [comment]
Forgot to add the potential fix.


        str.split(';').forEach((string) => {
            if (string !== '') {
              var attr = string.split(':');
                if(attr.length>2){
                 let attrName = attr.shift();
                    obj[attrName] = attr.join(":");
                }else{
                    obj[attr[0]] = attr[1];
                }
            }
        });

**Comment by z639** [comment]
hmm.. maybe even...

    str.split(';').forEach((string) => {
        if (string !== '') {
          let attr = string.split(':');
            if(attr.length>0){
             let attrName = attr.shift();
                obj[attrName] = attr.join(":");
            }
        }
    });

**Comment by RichardLitt** [comment]
This is a very good point. Would you be interested in making a PR? 

Ideally, adding a test case showing why this doesn't work would be good, too, so that we can catch that.
